import type { Task } from "@/lib/tasks"

export const fakeTasks: Task[] = [
  {
    id: "1",
    title: "Finish project report",
    description: "Complete the final draft of the project report and send it to the manager.",
    category: "Work",
    priority: "high",
    assignedDate: new Date("2025-09-20"),
    dueDate: new Date("2025-09-28"),
    progress: 70,
    completed: false,
  },
  {
    id: "2",
    title: "Buy groceries",
    description: "Milk, bread, eggs, and fruits",
    category: "Personal",
    priority: "medium",
    assignedDate: new Date("2025-09-23"),
    dueDate: new Date("2025-09-26"),
    progress: 10,
    completed: false,
  },
  {
    id: "3",
    title: "Gym workout",
    description: "Leg day training (squats, lunges, calf raises)",
    category: "Health",
    priority: "low",
    assignedDate: new Date("2025-09-24"),
    dueDate: new Date("2025-09-25"),
    progress: 100,
    completed: true,
  },
  {
    id: "4",
    title: "Prepare presentation",
    description: "Slides for Monday's client meeting",
    category: "Work",
    priority: "urgent",
    assignedDate: new Date("2025-09-22"),
    dueDate: new Date("2025-09-25"),
    progress: 40,
    completed: false,
  },
  {
    id: "5",
    title: "Read a book",
    description: "Continue reading 'Atomic Habits'",
    category: "Personal",
    priority: "low",
    assignedDate: new Date("2025-09-21"),
    dueDate: new Date("2025-10-05"),
    progress: 10,
    completed: false,
  },
]